config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :tweets do
    #      ruta         donde ira
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
    get 'detail', to: 'tweets#detail'
  end

  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # get 'users/follow'
  post 'follow/:user_id', to: 'users#follow', as: 'users_follow'

  get 'home/index'
  get 'all_whispers', to: 'home#all_whispers', as: 'all_whispers'
  get 'home/profile'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  include ActionView::Helpers::UrlHelper
  before_destroy :delete_tweet
  before_save :add_hashtags

  belongs_to :user
  #Canitdad de like
  has_many :likes, dependent: :destroy
  #Usuario que le dieron Like
  has_many :linking_users, :through => :likes, :source => :user

  validates :content, presence: true, length: { maximum: 140, too_long: "%{count} maximo de caracteres permitidos" }

  paginates_per 50

  scope :tweets_for_me, -> (user) { where(user_id: user.friends.pluck(:friend_id).push(user.id)) }

  def delete_tweet
    Tweet.where(rt_ref: self.id)
    Tweet.where(user_id: self.user_id).update_all(rt_ref: nil)
  end

  #metodo para agregar hashtag
  def add_hashtags
    new_array = []
    self.content.split(" ").each do |word|
      if word.start_with?("#") # #latam
        word_parsed = word.sub '#','%23'
        word = link_to( word, Rails.application.routes.url_helpers.root_path + "?search="+word_parsed )
      end
      new_array.push(word)
    end

    self.content = new_array.join(" ")
  end

  #metodo para saber si user le hizo like a un twitter
  def is_liked?(user)
    if self.linking_users.include?(user)#include lo busco dentro del hash
      true
    else
      false
    end
  end

  #Metodo para saber si esta re tweeteado
  def is_rt?(user, rt)
    if Tweet.where(user_id: user, rt_ref: rt).count == 0
      true
    else
      false
    end
  end

  #Eliminar Like
  def remove_like(user)
    Like.where(user: user, tweet:self).first.destroy
  end

  #Agregar Like
  def add_like(user)
    Like.create(user: user, tweet:self)
  end

  #Contar  Retweet
  def count_rt
    Tweet.where(rt_ref: self.id).count
  end

  #consulta si fue retweteado
  def is_retweet?
    rt_ref ? true : false
  end

  #Devuelve las referencias de retweets
  def tweet_ref
    Tweet.find(self.rt_ref)
  end

  #Devuelve lista de retweet
  def list_of_rt
    list = Tweet.where(rt_ref: self)
    return list
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :set_current_tweet, only: [:likes, :retweet]
  before_action :set_user_id, only: [:detail]

  #Metodo Like
  def likes
    if @tweet.is_liked?(current_user)
      @tweet.remove_like(current_user)
    else
      @tweet.add_like(current_user)
    end

    if current_user.present?
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  #Metodo retweet
  def retweet
    if current_user.present?
      if @tweet.is_rt?(current_user, @tweet.id)
        Tweet.create(content: @tweet.content, user: current_user, rt_ref: @tweet.id)
      else
        rm = Tweet.find_by(user_id: current_user, rt_ref: @tweet.id)
        rm.destroy
      end
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  #Metodo Detalle
  def detail
    if current_user.present?
      @user = User.find(@id)
      @following = @user.users_followed
      @follower = @user.my_follower
      @likes = @user.my_likes.order(created_at: :desc).page params[:page]
      @retweets = @user.retweets_give_it_now.order(created_at: :desc).page params[:page]
      @tweets = @user.my_tweets.order(created_at: :desc).page params[:page]
      @followed = @user.users_followed.count
      @follow = Friend.where(friend_id: @user).count
    else
      redirect_to new_user_session_path
    end
  end

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    if current_user.present?
      @tweets = @tweet.list_of_rt
    else
      redirect_to new_user_session_path
    end
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Whisper Posteado Correctamente' }
        format.json { render :show, status: :created, location: @tweet }
      else

        if @tweet.errors.any?
          @tweet.errors.full_messages.each do |message|
            if message.include? ".blank"
              format.html { redirect_to root_path, alert: "Post no puede ser solo espacios en blanco" }
            else
              format.html { redirect_to root_path, alert: "#{message}" }
            end
          end
        end
        #format.html { render :new }
        #format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_current_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    def set_user_id
      @id = params[:tweet_id]
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content,:user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<div class="mb-3">
  <%= form_with(model: tweet, local: true) do |form| %>
  
    <% if tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mb-3 text-11">
      <%#= form.label :content, '¿Que estas Pensando?' %>
      <%= form.text_area :content , placeholder: '¿Que estas Pensando...?', required: true, maxlength:"140", class: " text-11 form-control rounded-pill rounded ml-4", style: "width:90%; resize:none;" %>
    </div>
    <div class="border-up">
      <div class="actions mt-2 div-button-whispear">
        <%= form.submit "Whispear", class: "btn btn-primary btn-sm rounded-pill text-11"%>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/detail.html.erb
<%= render "shared/card_profile", tweet: @tweet %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>
index
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %></td>
        <td><%= tweet.user %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class="content-sec color-gray">
    <!--Title-->
    <div class="border-down pt-1 pl-4">
        <h5 class=""><%= link_to '<i class="fas fa-long-arrow-alt-left fa-lg color-blue text-decoration-none"></i>'.html_safe, root_path %>&nbsp;&nbsp;Destalle Whisper </h5>
    </div>

   <%= render "shared/card_tweet", tweet: @tweet %>
</div>

<!--Avatar de personas que le dieron Like-->
<div class="mx-4 pt-3">
  <div>
    <h6>Like <i class="fas fa-heart"></i></h6>
  </div>
  <div class="row">
    <div class="col-auto">
      <% @tweet.linking_users.each do |user| %>
        <%= link_to (image_tag (user.photo_url), 
          class: 'photo-avatar-post-re rounded-circle caja'), 
          tweet_detail_path(user), 
          class: 'tooltips', 
          title: '', 
          data: { toggle: 'tooltip', placement: 'left', original_title: "#{user.username}" }
        %>
      <% end %>
    </div>
  </div>
</div>

<!--Avatar de personas que le dieron ReTweetear-->
<div class="mx-4 pt-3">
  <div>
    <h6>Re-Whispear <i class="fas fa-retweet"></i></h6>
  </div>
   <div class="row">
    <div class="col-auto">
      <% @tweets.each do |tweet| %>
        <%= link_to (image_tag (tweet.user.photo_url), class: 'photo-avatar-post-re rounded-circle caja'), tweet_detail_path(tweet.user_id), class: 'tooltips', title: '', data: { toggle: 'tooltip', placement: 'left', original_title: "#{tweet.user.username}" } %>      
      <% end %>
    </div>
  </div>
</div>