config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :tweets do
    #      ruta         donde ira
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
    get 'detail', to: 'tweets#detail'
  end

  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # get 'users/follow'
  post 'follow/:user_id', to: 'users#follow', as: 'users_follow'

  get 'home/index'
  get 'all_whispers', to: 'home#all_whispers', as: 'all_whispers'
  get 'home/profile'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_card_profile.html.erb
<div class="content-sec color-gray">
    <!--Title-->
    <div class="border-down border-up pt-1 pl-4">
        <h6 class=""><%= link_to '<i class="fas fa-long-arrow-alt-left fa-lg color-blue"></i>'.html_safe, root_path %>&nbsp;&nbsp;@<%= @user.username%> | 
         <span class="text-13">&nbsp;&nbsp;<%= @user.my_tweets.count%>&nbsp;&nbsp;Whispers</span></h6>
    </div>

    <!--Profile-->
    <div class="">
        <!--Header Photo-->
        <div class="border-down contenerdor-header" >
            <%= image_tag(@user.header_photo, class: "photo-header", style:"width:100%; height:240px;") %>
        </div>
        <!--Avatar Photo-->
        <div class="">
            <%= image_tag(@user.photo_url, class: "perfil_photo rounded-circle ") %>
        </div>
        <!--Boton Photo-->
        <div class="">
            <% if current_user != @user %>
                <% if current_user.is_following?(@user)%>
                    <%= link_to '<i class="fas fa-minus"></i>&nbsp;&nbsp;Dejar de seguir'.html_safe, users_follow_path(@user.id), class:"rounded-pill btn btn-danger text-11 button-perfil", method: :post %>
                <% else %>
                    <%= link_to '<i class="fas fa-plus"></i>&nbsp;&nbsp;Seguir'.html_safe, users_follow_path(@user.id), class:"rounded-pill btn btn-success text-11 button-perfil", method: :post %>
                <% end %>
            <% else %>
                <%= link_to "Editar perfil", edit_user_registration_path, class: "rounded-pill btn btn-outline-info text-11 button-perfil" %>
            <% end %>
        </div>
        <!--Datos de perfil-->
        <div class="mt-5 pt-4 date-perfil">
            <span class="text-warning">@<%= @user.username %></span><br>
            <i class="fas fa-envelope color-gray text-13"></i><span class="color-gray text-8">&nbsp; <%= @user.email %></span><br>
            <i class="fas fa-calendar-check color-gray text-13"></i><span class="color-gray text-8">&nbsp; Miembro desde el     <%=  I18n.l(@user.created_at, format: '%A, %d de %B de %Y') %></span><br>
            <span class="color-gray text-13"><%= @followed %> Siguiendo</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="color-gray text-13"><%= @follow %> Siguidores</span>
        </div>
    </div>

    <!--Panel de posteos-->
    <div class="mt-4 pt-4">
        <div class="card mt-3 tab-card card-special rounded-0 border-down">
            <div class="card-header tab-card-header bg-whisper border-down rounded-0">
                <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="one-tab" data-toggle="tab" href="#one" role="tab" aria-controls="One" aria-selected="true">Whispers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="two-tab" data-toggle="tab" href="#two" role="tab" aria-controls="Two" aria-selected="false">Re - Whispers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="three-tab" data-toggle="tab" href="#three" role="tab" aria-controls="Three" aria-selected="false">Me gusta</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="four-tab" data-toggle="tab" href="#four" role="tab" aria-controls="Four" aria-selected="false">Siguiendo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="five-tab" data-toggle="tab" href="#five" role="tab" aria-controls="Five" aria-selected="false">Seguidores</a>
                    </li>
                </ul>
            </div>

            <div class="tab-content" id="myTabContent">
                <!--Whisper-->
                <div class="tab-pane fade show active bg-whisper" id="one" role="tabpanel" aria-labelledby="one-tab">
                    <!--Posteos-->
                    <% @tweets.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <!--Paginacion-->
                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @tweets, "Mostrar Menos Whisper", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @tweets.current_page %></i>
                            <%= link_to_next_page @tweets, "Mostrar Mas Whisper", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <!--Re Whisper-->
                <div class="tab-pane fade bg-whisper" id="two" role="tabpanel" aria-labelledby="two-tab">
                    <!--Posteos-->
                    <% @retweets.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <!--Paginacion-->
                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @retweets, "Mostrar Menos Whisper", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @retweets.current_page %></i>
                            <%= link_to_next_page @retweets, "Mostrar Mas Whisper", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <!--Me gusta-->
                <div class="tab-pane fade bg-whisper" id="three" role="tabpanel" aria-labelledby="three-tab">
                    <!--Posteos-->
                    <% @likes.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <!--Paginacion-->
                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @likes, "Mostrar Menos Whisper", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @likes.current_page %></i>
                            <%= link_to_next_page @likes, "Mostrar Mas Whisper", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <!--Siguiendo-->
                <div class="tab-pane fade bg-whisper" id="four" role="tabpanel" aria-labelledby="four-tab">
                    <% @following.each do |user| %>
                    <article class="whisper-post py-3"> 
                        <div class="row justify-content-md-center align-items-center">
                            <div class="col-1">
                                <%= link_to (image_tag (user.photo_url), 
                                    class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                                    tweet_detail_path(user)
                                %>
                            </div>
                            <div class="col-3">
                                <span class="text-warning text-13">@<%= user.username.capitalize %></span>
                            </div>
                            <div class="col-5">
                                <span class="color-gray text-13"><i class="fas fa-envelope color-gray text-13"></i>&nbsp;&nbsp;&nbsp;<%= user.email %></span>
                            </div>
                            <div class="col-2">
                                <%= link_to (@user.is_following?(user) ? "<i class='fas fa-user-minus text-warning text-13'></i>" : "<i class='fas fa-user-plus color-blue-deep text-13'></i>").html_safe, 
                                    users_follow_path(user.id), 
                                    class: "follow-btn",
                                    'title' => (@user.is_following?(user) ? "Dejar de Seguir" : "Seguir"),
                                    'data-toggle' => 'tooltip',
                                    'data-placement' => 'right',
                                    method: :post
                                %>
                            </div>
                        </div>
                    </article>
                    <% end %>
                </div>

                <!--Seguidores-->
                <div class="tab-pane fade bg-whisper" id="five" role="tabpanel" aria-labelledby="five-tab">
                     <% @follower.each do |user| %>
                    <article class="whisper-post py-3"> 
                        <div class="row justify-content-md-center align-items-center">
                            <div class="col-1">
                                <%= link_to (image_tag (user.photo_url), 
                                    class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                                    tweet_detail_path(user)
                                %>
                            </div>
                            <div class="col-3">
                                <span class="text-warning text-13">@<%= user.username.capitalize %></span>
                            </div>
                            <div class="col-5">
                                <span class="color-gray text-13"><i class="fas fa-envelope"></i>&nbsp;&nbsp;&nbsp;<%= user.email %></span>
                            </div>
                            <div class="col-2">
                            <% if current_user != user%>
                                <%= link_to (@user.is_following?(user) ? "<i class='fas fa-user-minus text-warning text-13'></i>" : "<i class='fas fa-user-plus color-blue-deep text-13'></i>").html_safe, 
                                    users_follow_path(user.id), 
                                    class: "follow-btn",
                                    'title' => (@user.is_following?(user) ? "Dejar de Seguir" : "Seguir"),
                                    'data-toggle' => 'tooltip',
                                    'data-placement' => 'right',
                                    method: :post
                                %>
                            <% end %>
                            </div>
                        </div>
                    </article>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_card_tweet.html.erb
 <!--Post Completo-->
<article class="whisper-post py-4">
    <!--Muestra si es retweet o tweet propio-->
    <% if tweet.is_retweet?%>
        <!--Es retweet-->
    <div class="zoom-post">
        <div class="zoom-post-row">
            <!--Fila 1-->
            <div class="row justify-content-center">
                <div class="col-7 pl-1">
                    <i class="fas fa-retweet color-tiara text-8"></i> <%=  link_to "#{tweet.user.username} re-Whispeo", tweet.tweet_ref, class:"color-tiara text-decoration-none text-8" %>
                    &nbsp;&nbsp;&nbsp;
                    <span class="text-11 color-tiara"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet), class: "color-tiara text-decoration-none" %></span>
                </div>
            </div>

            <!--Fila 2-->
            <div class="row mx-4 px-4">
                <div class="col- px-3">
                    <!--Avatar-->
                    <div class="mb-1">
                        <%= link_to (image_tag (tweet.tweet_ref.user.photo_url), 
                            class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                            tweet_detail_path(tweet.tweet_ref.user)
                        %>
                    </div>
                    <!-- Amigo-->
                    <% if user_signed_in? && current_user != tweet.user %>
                        <div class="text-center">
                            <%= link_to (current_user.is_following?(tweet.user) ? "<i class='fas fa-user-minus color-tiara ml-1 text-8'></i>" : "<i class='fas fa-user-plus color-danube ml-1 text-8'></i>").html_safe, 
                                users_follow_path(tweet.user.id), 
                                class: "follow-btn",
                                'title' => (current_user.is_following?(tweet.user) ? "Dejar de Seguir" : "Seguir"),
                                'data-toggle' => 'tooltip',
                                'data-placement' => 'right',
                                method: :post
                            %>
                        </div>
                    <% end %>
                </div>

                <div class="col-10 ">
                    <!--Nombre y fecha-->
                    <div>
                        <i class="text-13 text-warning"><strong>@<%= tweet.tweet_ref.user.username.capitalize %></strong></i>
                        &nbsp;&nbsp;&nbsp;
                        <span class="text-11 color-time"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.tweet_ref.user.created_at), tweet_path(tweet.tweet_ref), class: "color-time text-decoration-none" %></span>
                    </div>
                    <!--Detalle-->
                    <div class="text-11 border-down-white pb-2">
                        <span class="body-content">&nbsp;&nbsp;&nbsp;<%= tweet.content.html_safe %></span>
                    </div>

                    <!--Botones Likes y Re-Tweet-->
                    <div class="text-11 div-like-rewhisper pt-1">
                        <div class="row">
                            <!--Like-->
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_liked?(current_user) %>
                                        <%= link_to '<i class="fas fa-heart"></i>'.html_safe, 
                                            tweet_likes_path(tweet), 
                                            method: :post,
                                            class: "tooltips text-warning", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Quitar Like" }
                                        %>
                                    <% else %>
                                        <%= link_to '<i class="far fa-heart"></i>'.html_safe, 
                                            tweet_likes_path(tweet), 
                                            method: :post, 
                                            class: "text-white tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Like" }
                                        %>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.likes.count %>
                                </span>
                            </div>

                            <!--Retweet-->
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_rt?(current_user, tweet) %>
                                        <%= link_to '<i class="fas fa-retweet"></i>'.html_safe, 
                                            tweet_retweet_path(tweet), 
                                            method: :post, 
                                            class: "text-white text-decoration-none tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Re-Wispear" }
                                        %>
                                    <% else %>
                                        <%= link_to '<i class="fas fa-retweet"></i>'.html_safe, 
                                            tweet_retweet_path(tweet), 
                                            method: :post, 
                                            class: " text-warning text-decoration-none tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Quitar Re-Wispear" }%>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.count_rt %>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <% else %>
    <div class="zoom-post">
        <div class="zoom-post-row">
            <!--Es tweet-->
            <div class="row mx-4 px-4">
                <div class="col- px-3">
                    <!--Avatar-->
                    <div class="mb-1">
                        <%= link_to (image_tag (tweet.user.photo_url), 
                            class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                            tweet_detail_path(tweet.user_id)
                        %>
                    </div>
                    <!-- Amigo-->
                    <% if user_signed_in? && current_user != tweet.user %>
                        <div class="text-center ">
                            <%= link_to (current_user.is_following?(tweet.user) ? "<i class='fas fa-user-minus color-tiara ml-1 text-8'></i>" : "<i class='fas fa-user-plus color-danube ml-1 text-8'></i>").html_safe, 
                                users_follow_path(tweet.user.id), 
                                class: "follow-btn",
                                'title' => (current_user.is_following?(tweet.user) ? "Dejar de Seguir" : "Seguir"),
                                'data-toggle' => 'tooltip',
                                'data-placement' => 'right',
                                method: :post
                            %>
                        </div>
                    <% end %>
                </div>

                <div class="col-10 ">
                    <!--Nombre y fecha-->
                    <div>
                        <i class="text-13 text-warning"><strong>@<%= tweet.user.username.capitalize %></strong></i>
                        &nbsp;&nbsp;&nbsp;
                        <span class="text-11 color-time"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet), class: "color-time text-decoration-none" %></span>
                    </div>
                    <!--Detalle-->
                    <div class="text-11 border-down-white pb-2">
                        <span class="body-content">&nbsp;&nbsp;&nbsp;<%= tweet.content.html_safe %></span>
                    </div>

                    <!--Botones Likes y Re-Tweet-->
                    <div class="text-11 div-like-rewhisper pt-1">
                        <div class="row">
                            <!--Like-->
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_liked?(current_user) %>
                                        <%= link_to '<i class="fas fa-heart"></i>'.html_safe, 
                                            tweet_likes_path(tweet), 
                                            method: :post,
                                            class: "tooltips text-warning", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Quitar Like" }
                                        %>
                                    <% else %>
                                        <%= link_to '<i class="far fa-heart"></i>'.html_safe, 
                                            tweet_likes_path(tweet), 
                                            method: :post, 
                                            class: "text-white tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Like" }
                                        %>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.likes.count %>
                                </span>
                            </div>

                            <!--Retweet-->
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_rt?(current_user, tweet) %>
                                        <%= link_to '<i class="fas fa-retweet"></i>'.html_safe, 
                                            tweet_retweet_path(tweet), 
                                            method: :post, 
                                            class: "text-white text-decoration-none tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Re-Wispear" }
                                        %>
                                    <% else %>
                                        <%= link_to '<i class="fas fa-retweet"></i>'.html_safe, 
                                            tweet_retweet_path(tweet), 
                                            method: :post, 
                                            class: " text-warning text-decoration-none tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Quitar Re-Wispear" }%>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.count_rt %>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <% end %>
</article>

app/views/shared/_footer.html.erb
<footer class="footer-twitter fixed-bottom shadow-lg mt-5">
    <div class="row justify-content-center align-items-center text-white">
        <div class="col-7 p-1">
            <p class="h4"><strong>No te pierdas lo que está pasando</strong>
            <br>
            <i class="h5">Los usuarios de Whisper son los primeros en enterarse.</i>
            </p>
        </div>
        <div class="col-4 ml-5 pl-5">
            <%= link_to 'Iniciar Sesion', new_user_session_path , class:"btn btn-light rounded-pill text-primary m-2"%>
            <%= link_to "Registrarse", new_user_registration_path, class:"btn btn-light rounded-pill text-primary m-2"%>
        </div>
    </div>
</footer>

app/views/shared/_messages.html.erb
<div class="message-format pt-4 text-11">
    <% if alert.present? %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <i class="fas fa-exclamation-triangle fa-sm"></i>&nbsp;<strong>Alerta :</strong><i class="alert text-left"><%= alert %></i>
            <button type="button" class="close text-13" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>   
    <% elsif notice.present? %>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            <i class="fas fa-flag fa-sm"></i>&nbsp;<i class="alert text-left"><%= notice %></i>
            <button type="button" class="close text-13" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/shared/_navbar_left.html.erb
  <nav class="navbar-left">

    <!--Row Icon Twitter-->
    <div class="icon-twitter pb-1">
      <div class="row justify-content-center pt-4">
        <div class="col-auto">
          <span class="mt-3 text-center" style="float:right;">
            <%= link_to '<i class="fab fa-phoenix-framework fa-3x color-blue mr-3 zoom-icon"></i>'.html_safe, root_path %>
          </span>
          <p class="color-blue font-weight-bold whiper">WHISPER</p>
        </div>
      </div>
    </div>

    <!--Row Home-->
    <%if user_signed_in? %>
    <div class="row text-white mt-4 ">
      <div class="col-4 text-right pr-0">
        <i class="fas fa-house-damage fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
        <p><strong><%= link_to "Home", root_path, class: "text-decoration-none color-gray"%></strong></p>
      </div>
    </div>
    <% end %>

    <!--Row Explorar-->
    <div class="row text-white mt-0">
      <div class="col-4 text-right pr-0">
        <i class="fas fa-hashtag fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
        <p><strong><%= link_to "Explorar", all_whispers_path, class: "text-decoration-none color-gray"%></strong></p>
      </div>
    </div>

  <!--Validar Login-->
  <%if user_signed_in? %>
    <!--Row My Profile-->
    <div class="row text-white mt-0">
      <div class="col-4 text-right pr-0">
        <i class="fas fa-user fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
        <p><strong><%= link_to "Mi Perfil", home_profile_path, class: "text-decoration-none color-gray"%></strong></p>
      </div>
    </div>

    <!--Row Configuracion-->
    <div class="row text-white mt-0">
      <div class="col-4 text-right pr-0">
        <i class="fas fas fa-cog fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
        <p><strong><%= link_to "Configuracion", edit_user_registration_path, class: "text-decoration-none color-gray"%></strong></p>
      </div>
    </div>

    <!--Row Admin-->
    <% if current_user.admin %>
    <div class="row text-white mt-0">
      <div class="col-4 text-right pr-0">
        <i class="fas fa-tools fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
        <p><strong><%= link_to "Administracion", admin_user_path(current_user), class: "text-decoration-none color-gray"%></strong></p>
      </div>
    </div>
    <% end %>
    
    <!--Row Cerrar Sesion-->
      <div class="rounded-pill mx-2 devise-how pb-2">
        <div class="row justify-content-md-center align-items-center"  >
          <div class="col-2">
            <%= image_tag(current_user.photo_url, class: "photo-avatar-session rounded-circle ", alt: "Avatar Session")%>
          </div>
          <div class="col-6">
            <strong><i class="text-warning text-13">@<%= current_user.username.capitalize %></i></strong><br>
            <i class="color-gray text-8"><i class="fas fa-envelope">&nbsp;</i><%= current_user.email %></i>
          </div>
          <div class="col-1 " style="margin:0px; padding:0px;">
            <i class="fas fa-angle-down fa-lg text-white btn"  style="margin:0px; padding:0px;"  data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1"></i>
          </div>
        </div>
      </div>

      <!--Collapse Boton-->
      <div class="row">
        <div class="col">
          <div class="collapse multi-collapse" id="multiCollapseExample1">
            <div class="card card-body bg-gray rounded-0" >
              <%= link_to '<i class="fas fa-sign-out-alt"></i>&nbsp;Cerrar Sesion'.html_safe , destroy_user_session_path, method: :get, class: "text-center font-weight-bolder border-white text-white text-13" %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  </nav>