config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :tweets do
    #      ruta         donde ira
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
    get 'detail', to: 'tweets#detail'
  end

  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # get 'users/follow'
  post 'follow/:user_id', to: 'users#follow', as: 'users_follow'

  get 'home/index'
  get 'all_whispers', to: 'home#all_whispers', as: 'all_whispers'
  get 'home/profile'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if signed_in?
      if( params[:search] && !params[:search].empty? )
        @tweets = Tweet.tweets_for_me(current_user).where("content LIKE ?", "%#{params[:search]}%").order(created_at: :desc).page params[:page]
      else
        #Mostrar solo lo de los amigos y los mios
        @tweets = Tweet.tweets_for_me(current_user).order(created_at: :desc).page params[:page]
      end
      @tweet = Tweet.new
    else
      #Muestra todo
      @tweets = Tweet.order(created_at: 'desc').page params[:page]
      redirect_to all_whispers_path
    end
  end

  def all_whispers
    if( params[:search] && !params[:search].empty? )
      @tweets = Tweet.where("content LIKE ?", "%#{params[:search]}%").order(created_at: :desc).page params[:page]
    else
      #Mostrar Todo
      @tweets = Tweet.order(created_at: 'desc').page params[:page]
    end


    #Muestra todo
    #@tweets = Tweet.order(created_at: 'desc').page params[:page]
    #@tweet = Tweet.new
    #@trendingTopic = trendingTopic
    #Plantilla para reutilizar vista
    #render :template => "home/index"
  end

  def profile
    if current_user.present?
      @following = current_user.users_followed
      @follower = current_user.my_follower
      @likes = current_user.my_likes.order(created_at: :desc).page params[:page]
      @retweets = current_user.retweets_give_it_now.order(created_at: :desc).page params[:page]
      @tweets = current_user.my_tweets.order(created_at: :desc).page params[:page]
      @followed = current_user.users_followed.count
      @follow = Friend.where(friend_id: current_user).count
    else
      redirect_to new_user_session_path
    end
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/all_whispers.html.erb
<div class="content-sec color-gray">
    <!--Title-->
    <div class="border-down pt-1 pl-4">
        <h5 class=""><%= link_to '<i class="fas fa-long-arrow-alt-left fa-lg color-blue"></i>'.html_safe, root_path %>&nbsp;&nbsp;Explorar</h5>
    </div>

    <!--Posteos-->
    <% @tweets.each do |tweet| %>
        <%= render "shared/card_tweet", tweet: tweet %>
    <% end %>

    <!--Paginacion-->
    <div class="p-4">
        <div class="text-center">
            <%= link_to_prev_page @tweets, "Mostrar Menos Whisper", class: "btn btn-primary btn-sm text-11" %>
            <i class="btn btn-light btn-sm text-13 "><%= @tweets.current_page %></i>
            <%= link_to_next_page @tweets, "Mostrar Mas Whisper", class:"btn btn-primary btn-sm text-11"%>
        </div>
    </div>
    <%#= paginate @tweets %>
</div>

app/views/home/index.html.erb
<div class="content-sec color-gray">
    <!--Title-->
    <div class="border-down pt-1 pl-4">
        <h5 class="">Inicio</h5>
    </div>

    <!--Mensajeria-->
    <%= render "shared/messages"%>

    <!--Nuevo Post-->
    <% if user_signed_in? %>
        <div class="border-down">
            <div class="row justify-content-md-center">
                <div class="col-1 mr-3">
                    <%= image_tag(current_user.photo_url, class: "photo-avatar rounded-circle ", alt: "Avatar Session")%>
                </div>
                <div class="col-9">
                <!--Renderizar formulario tweet -->
                <%= render 'tweets/form', tweet: @tweet %>
                </div>
            </div>
        </div>
    <% end %>

    <!--Posteos-->
    <% @tweets.each do |tweet| %>
        <!--Post Completo-->
        <span></span>
        <article class="whisper-post py-3"> 
            <div class="row justify-content-md-center">
                <!--Avatar Post-->
                <div class="col-1">
                    <%= image_tag(tweet.user.photo_url, class: "photo-avatar-post rounded-circle ", alt: "Avatar Post")%>
                </div>
                <!--Nombre y Detalle -->
                <div class="col-9">
                    <!--Fecha --->
                    <span class="text-11 color-time"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.created_at), tweet, class: "color-time text-decoration-none" %></span>
                    <!--Nombre-->
                    <div>
                        <i class="text-13 color-blue-deep"><strong>@<%= tweet.user.username.capitalize %></strong></i>
                    </div>
                    <!--Detalle-->
                    <div class="text-11 border-down-white pb-2">
                            <!--Muestra si es retweet o tweet propio-->
                            <% if tweet.is_retweet?%>
                                <!--Retweet-->
                                <%=  link_to "", tweet.tweet_ref, class:"fas fa-registered fa-lg text-warning text-decoration-none" %>
                                <div class="row justify-content-md-center retweet-marco rounded-pill py-2 px-2">
                                    <div class="col-2">
                                        <%= image_tag(tweet.tweet_ref.user.photo_url, class: "photo-avatar-post-re rounded-circle ", style: "float:left;" ,alt: "Avatar Post")%>
                                    </div>
                                    <div class="col-10 " style="padding-left:0%; padding-right:10%;">
                                        <!--Fecha --->
                                        <span class="text-11 color-time"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.tweet_ref.created_at), tweet, class: "color-time text-decoration-none" %></span>
                                        <br>
                                        <!--Nombre-->
                                        <strong class="color-blue ">@<%= tweet.tweet_ref.user.username.capitalize %></strong>
                                        <br>
                                        <!--Contenido-->
                                        <span><%= tweet.tweet_ref.content %></span>>
                                    </div>
                                </div>
                            <% else %>
                                <!--Comentario tweet propio-->
                                &nbsp;&nbsp;&nbsp;<%= tweet.content %>
                            <% end %>
                    </div>

                    <!--Botones Likes y Re-Tweet-->
                    <div class="text-11 div-like-rewhisper pt-1">
                        <div class="row">
                            <!--Like-->
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_liked?(current_user) %>
                                        <%= link_to '<i class="fas fa-heart"></i>'.html_safe, tweet_likes_path(tweet), method: :post, class: "text-warning" %>
                                    <% else %>
                                        <%= link_to '<i class="far fa-heart"></i>'.html_safe, tweet_likes_path(tweet),method: :post, class: "text-white" %>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.likes.count %>
                                </span>
                            </div>
                            <!--Retweet-->
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_rt?(current_user, tweet) %>
                                        <%= link_to '', tweet_retweet_path(tweet), method: :post, class: "fas fa-retweet text-white text-decoration-none"%>
                                    <% else %>
                                        <%= link_to '', tweet_retweet_path(tweet), method: :post, class: "fas fa-retweet text-warning text-decoration-none"%>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.count_rt %>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    <% end %>

    <!--Paginacion-->
    <div class="p-4">
        <div class="text-center">
            <%= link_to_prev_page @tweets, "Mostrar Menos Whisper", class: "btn btn-primary btn-sm text-11" %>
            <i class="btn btn-light btn-sm text-13 "><%= @tweets.current_page %></i>
            <%= link_to_next_page @tweets, "Mostrar Mas Whisper", class:"btn btn-primary btn-sm text-11"%>
        </div>
    </div>
    <%#= paginate @tweets %>
</div>

app/views/home/profile.html.erb
<div class="content-sec color-gray">
    <!--Title-->
    <div class="border-down border-up pt-1 pl-4">
        <h6 class=""><%= link_to '<i class="fas fa-long-arrow-alt-left fa-lg color-blue"></i>'.html_safe, root_path %>&nbsp;&nbsp;@<%= current_user.username%> | 
         <span class="text-13">&nbsp;&nbsp;<%= current_user.my_tweets.count%>&nbsp;&nbsp;Whispers</span></h6>
    </div>

    <!--Profile-->
    <div class="">
        <!--Header Photo-->
        <div class="border-down contenerdor-header" >
            <%= image_tag(current_user.header_photo, class: "photo-header", style:"width:100%; height:240px;") %>
        </div>
        <!--Avatar Photo-->
        <div class="">
            <%= image_tag(current_user.photo_url, class: "perfil_photo rounded-circle ") %>
        </div>
        <!--Boton Photo-->
        <div class="">
            <%= link_to "Editar perfil", edit_user_registration_path, class: "rounded-pill btn btn-outline-info text-11 button-perfil" %>
        </div>
        <!--Datos de perfil-->
        <div class="mt-5 pt-4 date-perfil">
            <span class="text-warning">@<%= current_user.username %></span><br>
            <i class="fas fa-envelope color-gray text-13"></i><span class="color-gray text-8">&nbsp; <%= current_user.email %></span><br>
            <i class="fas fa-calendar-check color-gray text-13"></i><span class="color-gray text-8">&nbsp; Miembro desde el     <%=  I18n.l(current_user.created_at, format: '%A, %d de %B de %Y') %></span><br>
            <span class="color-gray text-13"><%= @followed %> Siguiendo</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="color-gray text-13"><%= @follow %> Siguidores</span>
        </div>
    </div>

    <!--Panel de posteos-->
    <div class="mt-4 pt-4">
        <div class="card mt-3 tab-card card-special rounded-0 border-down">
            <div class="card-header tab-card-header bg-whisper border-down rounded-0">
                <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="one-tab" data-toggle="tab" href="#one" role="tab" aria-controls="One" aria-selected="true">Whispers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="two-tab" data-toggle="tab" href="#two" role="tab" aria-controls="Two" aria-selected="false">Re - Whispers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="three-tab" data-toggle="tab" href="#three" role="tab" aria-controls="Three" aria-selected="false">Me gusta</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="four-tab" data-toggle="tab" href="#four" role="tab" aria-controls="Four" aria-selected="false">Siguiendo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="five-tab" data-toggle="tab" href="#five" role="tab" aria-controls="Five" aria-selected="false">Seguidores</a>
                    </li>
                </ul>
            </div>

            <div class="tab-content" id="myTabContent">
                <!--Whisper-->
                <div class="tab-pane fade show active bg-whisper" id="one" role="tabpanel" aria-labelledby="one-tab">
                    <!--Posteos-->
                    <% @tweets.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <!--Paginacion-->
                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @tweets, "Mostrar Menos Whisper", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @tweets.current_page %></i>
                            <%= link_to_next_page @tweets, "Mostrar Mas Whisper", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <!--Re Whisper-->
                <div class="tab-pane fade bg-whisper" id="two" role="tabpanel" aria-labelledby="two-tab">
                    <!--Posteos-->
                    <% @retweets.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <!--Paginacion-->
                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @retweets, "Mostrar Menos Whisper", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @retweets.current_page %></i>
                            <%= link_to_next_page @retweets, "Mostrar Mas Whisper", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <!--Me gusta-->
                <div class="tab-pane fade bg-whisper" id="three" role="tabpanel" aria-labelledby="three-tab">
                    <!--Posteos-->
                    <% @likes.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <!--Paginacion-->
                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @likes, "Mostrar Menos Whisper", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @likes.current_page %></i>
                            <%= link_to_next_page @likes, "Mostrar Mas Whisper", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <!--Siguiendo-->
                <div class="tab-pane fade bg-whisper" id="four" role="tabpanel" aria-labelledby="four-tab">
                    <% @following.each do |user| %>
                    <article class="whisper-post py-3"> 
                        <div class="row justify-content-md-center align-items-center">
                            <div class="col-1">
                                <%= link_to (image_tag (user.photo_url), 
                                    class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                                    tweet_detail_path(user)
                                %>
                            </div>
                            <div class="col-3">
                                <span class="text-warning text-13">@<%= user.username.capitalize %></span>
                            </div>
                            <div class="col-5">
                                <span class="color-gray text-13"><i class="fas fa-envelope color-gray text-13"></i>&nbsp;&nbsp;&nbsp;<%= user.email %></span>
                            </div>
                            <div class="col-2">
                                <%= link_to (current_user.is_following?(user) ? "<i class='fas fa-user-minus text-warning text-13'></i>" : "<i class='fas fa-user-plus color-blue-deep text-13'></i>").html_safe, 
                                    users_follow_path(user.id), 
                                    class: "follow-btn",
                                    'title' => (current_user.is_following?(user) ? "Dejar de Seguir" : "Seguir"),
                                    'data-toggle' => 'tooltip',
                                    'data-placement' => 'right',
                                    method: :post
                                %>
                            </div>
                        </div>
                    </article>
                    <% end %>
                </div>

                <!--Seguidores-->
                <div class="tab-pane fade bg-whisper" id="five" role="tabpanel" aria-labelledby="five-tab">
                     <% @follower.each do |user| %>
                    <article class="whisper-post py-3"> 
                        <div class="row justify-content-md-center align-items-center">
                            <div class="col-1">
                                <%= link_to (image_tag (user.photo_url), 
                                    class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                                    tweet_detail_path(user)
                                %>
                            </div>
                            <div class="col-3">
                                <span class="text-warning text-13">@<%= user.username.capitalize %></span>
                            </div>
                            <div class="col-5">
                                <span class="color-gray text-13"><i class="fas fa-envelope"></i>&nbsp;&nbsp;&nbsp;<%= user.email %></span>
                            </div>
                            <div class="col-2">
                                <%= link_to (current_user.is_following?(user) ? "<i class='fas fa-user-minus text-warning text-13'></i>" : "<i class='fas fa-user-plus color-blue-deep text-13'></i>").html_safe, 
                                    users_follow_path(user.id), 
                                    class: "follow-btn",
                                    'title' => (current_user.is_following?(user) ? "Dejar de Seguir" : "Seguir"),
                                    'data-toggle' => 'tooltip',
                                    'data-placement' => 'right',
                                    method: :post
                                %>
                            </div>
                        </div>
                    </article>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>